//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dynamo.Applications.AdvanceSteel.Services {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dynamo.Applications.AdvanceSteel.Services.ResourceStrings", typeof(ResourceStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The location of the assembly, {0} could not be resolved for loading.
        /// </summary>
        public static string Application_AssemblyNotResolved {
            get {
                return ResourceManager.GetString("Application_AssemblyNotResolved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An instance of Model is required to construct a View Model..
        /// </summary>
        public static string Application_ConstructorViewModel {
            get {
                return ResourceManager.GetString("Application_ConstructorViewModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document &apos;{0}&apos; is closed..
        /// </summary>
        public static string Application_DocumentClosed {
            get {
                return ResourceManager.GetString("Application_DocumentClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dynamo is not pointing at the document &apos;{0}&apos;..
        /// </summary>
        public static string Application_DocumentInvalid {
            get {
                return ResourceManager.GetString("Application_DocumentInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dynamo is now running on document &apos;{0}&apos;..
        /// </summary>
        public static string Application_DocumentRunning {
            get {
                return ResourceManager.GetString("Application_DocumentRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It&apos;s not possible open more than one Dynamo instance.
        /// </summary>
        public static string Application_DynamoOneInstance {
            get {
                return ResourceManager.GetString("Application_DynamoOneInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The RunButton is disabled because Dynamo is not bound to the current active document..
        /// </summary>
        public static string Application_LogRunButtonDisabled {
            get {
                return ResourceManager.GetString("Application_LogRunButtonDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please open a document..
        /// </summary>
        public static string Application_NoDocument {
            get {
                return ResourceManager.GetString("Application_NoDocument", resourceCulture);
            }
        }
    }
}
